### ISSUE TITLE
$endpoint not defined in get_item_of_type()

### ISSUE THREAD

**Issue by jesseves** [tamw-wnet/PBS_Media_Manager_Client#17]
I just pulled down the updated master, and I'm seeing an error in `get_item_of_type()` that wasn't there previously.

The query is built using the `$query` variable, but that never gets used. Instead the function ends with

`return $this->get_request($endpoint . $querystring);`

But `$endpoint` is never defined.

**Comment by tamw-wnet** [comment]
doh.  I got sloppy with my merge.  I've fixed with 920ea86

**Comment by tamw-wnet** [comment]
and still sloppy.   ef6e821

**Comment by tamw-wnet** [comment]
That _should_ fix it, @jesseves .  Friday afternoon merges should never be pushed until Tuesday!

**Comment by jesseves** [comment]
There we are!  All yellows, no reds.

(And agreed!)
