### ISSUE TITLE
audience-scope helper function

### ISSUE THREAD

**Issue by tamw-wnet** [tamw-wnet/PBS_Media_Manager_Client#23]
@augustuswm @acrosman @jesseves PBS has done something irritating with their 'audience-scope' argument.   In the documentation, it can be a comma-separated list aka audience-scope=national,local but in actual practice audience-scope has to be separate query elements, in an order eg audience-scope=national&audience-scope=local.

This is problematic for our 'queryargs' named array element strategy, because if you set an array with two elements that have the same key ('audience-scope'=>'local', 'audience-scope'=>'national', only one of them is gonna be preserved when we generate our query string.

I propose to build into the 'build_pbs_querystring' function logic to split up 'audience-scope'=> 'local,national' into separate elements in the querystring.   Or we could wait for PBS to fix their stuff to follow their documentation.

thoughts?

**Comment by tamw-wnet** [comment]
Or we could setup 'audience-scope' as being either a string or an array; either 'audience-scope' => 'local' or 'audience-scope' => array('local','national','allstations').  In the current setup, that gives us
https://media.services.pbs.org/api/v1/shows/?audience=wnet&audience-scope[0]=local&audience-scope[1]=national&audience-scope[2]=all-stations

which doesn't return useful data, but if I strip out the [0][1][2] it should.

**Comment by augustuswm** [comment]
My initial reaction is supporting both a string and array style.

Stringy values explode into multiple arguments and array arguments become multiple instances.

Ultimately I don't think the decision should be visible to the user using the client (unless they are inspecting the url). End user should use be able to use the client the same way, independent of if the API implements the parameter as multiple single values or a comma separated list.  Probably all arguments that support multiple values should support both string and array versions, and should translate to API representations as necessary.

Edited after re-reading.

**Comment by augustuswm** [comment]
Ignore my comment. I completely misread what the issue was.

**Comment by tamw-wnet** [comment]
You know, I think we're going to run into the same issue with multiple platform-slug values.   If I try and retrieve a list with array('platform-slug' => 'partnerplayer', 'platform-slug' => 'bento'), that's going to actually just do the 'bento' platform-slug value.   We'll need to specify platform-slug as taking either a string or an array, and then I'll strip out the [0] [1] [2] etc from the query string since PBS doesn't understand those.

**Comment by tamw-wnet** [comment]
Wow, there's even more -- not only can 'audience-scope' contain multiple values, but so can 'audience'.  This is mostly an issue for me (we have local shows for WNET, WLIW, and WNTJ that we share on the websites for all three stations).   I'm updating the documentation and function that anytime we have multiple values for a querystring arg they should be passed as an array, and then I'll strip off any (encoded) [0] [1] etc since PBS ignores those.

**Comment by tamw-wnet** [comment]
69d73e0bb300f6985366a04f76f376f68d9a3204 handles this.

**Comment by tamw-wnet** [comment]
btw, my bad -- I just did a force-push to fix an error in my latest commit message.   So if you've tried to pull since I committed that, you'll need to discard and repull probably.
