### ISSUE TITLE
Is there a return_count parameter you are aware of?

### ISSUE THREAD

**Issue by not-original** [tamw-wnet/PBS_Media_Manager_Client#29]
Been through the docs, but can't seem to find the proper parameter for a return count.  If, for example, I wish to only return 5 episodes, or 7 clips, etc. 

I tried page-size, and page, but while page limited to 50,  page-size had no effect. 

Basically, if I want to return only the last 5 Full length episodes of a show:

$output = $client->get_list_data('/assets/', array('show-id'=>$cid,'type'=>'full_length', 'platform_slug' => 'partnerplayer', 'sort' =>'-premiered_on', 'page'=>1) );

Any help appreciated.

**Comment by augustuswm** [comment]
I thought that page and page-size were the appropriate parameters to call with.

For instance to get the second page of full length results (split into pages of 5 each) and ordered by their premiere date:

```
https://media.services.pbs.org/api/v1/assets/?show-id=37d91f73-ccea-4266-8ce0-28a5b6a857d2&platform-slug=partnerplayer&page-size=5&page=2&type=full_length&sort=-premiered_on
```

and I think that should translate to 

```php
 $client->get_list_data(
  '/assets/',
  array(
    'show-id' => '37d91f73-ccea-4266-8ce0-28a5b6a857d2',
    'page-size' => 5,
    'page' => 2,
    'type' => 'full_length',
    'platform-slug' => 'partnerplayer',
    'sort' => '-premiered_on'
  )
);
```

If I remember I think `get_list_data` requires the page parameter to be passed in to make it limit to a single page (as opposed to multiple pages).

Are you seeing different behavior? ie returning more / less / wrong page?

**Comment by not-original** [comment]
Hey @augustuswm 

I misunderstood.  I didn't realize you needed to send both parameters.   I was just using 'page-size' =>5, thinking that would return just one page of five. 

    'page-size' => 5,
    'page' => 1,

Works just fine, thanks!
