### ISSUE TITLE
Possible to Return Seasons that Only Contain Full Length Episodes?

### ISSUE THREAD

**Issue by not-original** [tamw-wnet/PBS_Media_Manager_Client#31]
Hey Tam, 

Not sure if this is possible, but wanted to check. 

I am trying to return only those seasons for a show that contain full length episodes. 

For example, on this call:
$seasons=$client->get_show_seasons('adfb2f9d-f61e-4613-ac58-ab3bde582afb');

I get season 45, which only contains a preview.  Not a full length episode. 

I tired adding parameters such as 

$seasons=$client->get_show_seasons('adfb2f9d-f61e-4613-ac58-ab3bde582afb', array('type'=>'full_length',  'platform_slug' => 'partnerplayer' ));

But it had no effect, which I wouldn't expect that it would. 

I tried adding 'fetch-related', as well.  And while that gave me assets,  it still didn't define whether those are Full Length or not. 

I thought, perhaps, I could cycle through each season and see if there was a full length episode in there and perform some logic:

	foreach($seasons as $season){
	$output=$client->get_season_episodes($season['id'], array('type'=>'full_length',  'platform_slug' => 'partnerplayer' ));
	print_r($output);
	}

But that still returned the episode that only had previews. 

I did manage to create a query, but it was way too complex and took more than 20 seconds to run, where I cycled through each season, and each episode to see if there was a full length in there and then push that season and ID to an array to publish.  But, I really need this to be under 2 seconds or so. 

If you have any thoughts or ideas, I would appreciate hearing them.  As always, thanks for your time. 

Chet

**Comment by acrosman** [comment]
Do you want the actual season information or are you just looking for a way to pull full episodes?  In the Drupal module we've run into a similar issue when trying to get list of recent episodes for a given show.  Originally we were iterating over seasons to find them, but that's problematic and incredibly slow since you have to run lots of queries against the API.

Turns out that wasn't needed. @jesseves noticed that we could just query for show assets that are type "full-length", platform-plug "partner-player", and sorted by premier date. It's a drastically more efficient solution.

Requires the most recent version of library (anything after PR 26) which adds the get_assets() method.

**Comment by not-original** [comment]
Hey Arron, 

No, I am just trying to get the season IDs for show seasons that have full length episodes. 

Right now, a call to display the season IDs for show returns all seasons that have assets. 

For example, this call:
$seasons=$client->get_show_seasons('adfb2f9d-f61e-4613-ac58-ab3bde582afb');

Returns 45(ish) season IDs. 

However, Season 45 has no full-length assets so I don't want it returned.  

I was trying to find a way to make a call where only those seasons that HAVE full length episodes are returned.  Without having to go through each season (or each episode).

**Comment by jesseves** [comment]
Hmmm... I don't see anything in the documentation that describes what you're trying to do, so this sounds like a limitation on the API, not the client.   You may want to ask PBS instead. http://digitalsupport.pbs.org/support/discussions/12000000201

**Comment by not-original** [comment]
@jesseves Yeah, I thought so.  I think 'episodes' are returned in a season, once any asset has been added to that season (regardless of type).  I'll post over there and see if they have any solutions. 

Thanks for you help.

**Comment by tamw-wnet** [comment]
I haven't tested this, but there _is_ a way to get all of the assets for a show.

**Comment by tamw-wnet** [comment]
sorry, clicked too soon -- 
https://media.services.pbs.org/api/v1/assets/?show-id={show_id}&type=full_length  will get a list of assets for a show.  Maybe you could go through the list of seasons, and foreach do a 
https://media.services.pbs.org/api/v1/assets/?season-id={season_id}&type=full_length
and if that call got a non-null result, that's a season of the sort you're looking for.

**Comment by not-original** [comment]
Hey Tam,
Thanks for the reply.  That was that query I mentioned in my original comment.  Although it does work, it just takes way too long on some series.  For example, Nature has 45 seasons to cycle through -- which is 45 calls to the API, plus the original season call. 

That's why I was kinda hoping I was missing some way to get additional meta data about each season such as number of assets and asset types by adding 'fetch related' or similar.  

As always, I appreciate the help.  But I think I may need to find another way to accomplish what I need.

**Comment by tamw-wnet** [comment]
Well, if it helps anything, Nature may have seasons enumerated up to 45, but it actually 'only' has 23 seasons.
