### ISSUE TITLE
Search Assets for a Particular Show

### ISSUE THREAD

**Issue by not-original** [tamw-wnet/PBS_Media_Manager_Client#32]
Sorry for leaving this here, but hoping maybe one of you have encountered this issue.  I would post at PBS Digital Forums, but it seems like that is where questions go to die. 

I am trying to develop a search of assets based on a show. 

For example,  show me all assets with **Cincinnati** in the title for **Antiques Roadshow**. 

However, if I make a call to 
https://media.services.pbs.org/api/v1/assets/search/?show-title=Antiques+Roadshow&asset-title=Cincinnati

It returns all assets in the system with Cincinnati in the title. 

The docs state:
If searching using asset-title the endpoint will return all assets (clip, full_length, preview) with a title matching the passed asset-title argument. This argument can not be chained with other search arguments; also, it does not support requests chaining more asset-title arguments.

So, I feel I might be out of luck.  The only thing I can think of doing is pulling in ALL the assets for the title first, and then cycling through to see if the show matches-- which seems insane. 

Just wondering if anybody has another suggestion. 

Thanks for any help!

**Comment by augustuswm** [comment]
I haven't looked too much into search, but I think your interpretation is correct. From what I am reading asset-title is not available for combining with other filters.

Maybe someone else has a good recommendation on searching assets via the API?

**Comment by tamw-wnet** [comment]
@not-original I don't have a great answer for you either, but you might get some traction in the station-to-station forum.  http://digitalsupport.pbs.org/support/discussions/12000000097  Maybe somebody at another station has an alternate strategy?
