### ISSUE TITLE
make_response_array errors on API failure

### ISSUE THREAD

**Issue by augustuswm** [tamw-wnet/PBS_Media_Manager_Client#34]
A call we are making to `create_child` fails with the below error. This calls to `make_response_array` which errors when trying to parse with an unset index error at:

```PHP
$middle = explode(": ", $part, 2);
$myarray[trim($middle[0])] = trim($middle[1]);
```

```
HTTP/1.1 400 Bad Request
Server: nginx
Date: Sat, 24 Feb 2018 10:16:02 GMT
Content-Type: application\/json
Content-Length: 77
Connection: keep-alive
Allow: GET, POST, HEAD, OPTIONS
Vary: Accept
X-Frame-Options: SAMEORIGIN

{"errors":{"meta":{"ordinal":["Episode with this ordinal already exists."]}}}
```

Should `make_response_array` have a block similar to `get_request` that is checking for json-like bodies?

**Comment by tamw-wnet** [comment]
That's an excellent idea.

**Comment by augustuswm** [comment]
Looks like there is already a check for parsing json like lines in the response. Let me dig a bit and see why this was erroring.

Going to close this. I think JSON parsing is fine, it was a related parsing, but different issue.
