### ISSUE TITLE
Account for inconsistent CURL header labels

### ISSUE THREAD

**Issue by pdmytrewycz** [tamw-wnet/PBS_Media_Manager_Client#41]
I was pulling my hair out trying to figure out why create_child() wasn't returning the pbs_content_id of my newly created Episode (with which I would then create a new Asset). Episode creation was successfull, but the call was returning _null_ for the new Episode's pbs_content_id.

But only on _some_ AWS instances!

Ultimately, thru a full day's worth of debugging, I figured it out. The CURL headers returned by PBS are not always capitalized! depending, I think, either on the CURL implementation or the PHP version. Your client uses the resultant CURL headers, specifically "Location", to parse out the new child's pbs_content_id. (Let's set aside the fact that burying the most important bit of information about a post result in the headers is pretty much THE most unhelpful way to do it; thanks PBS... )

You use regex to preg_match() the "Location" header from the full string of headers, but the regex is case-sensitive. Thus, a header of "location" is not matched like "Location".
 
I ended up writing a separate private function, mimicing what create_child() does, but using the following to parse the pbs_content_id out of the CURL headers:
 
 **foreach ( preg_split('/\r\n?/', $result) as $header ) {
      if ( stripos($header, 'location') !== false ) {
          $loc_array = explode('/', rtrim($header,'/'));
          return end($loc_array);
     }
}**

It's slightly heavier than your single regex approach, but using stripos() makes it case-insensitive. (I lack the regex skills to modify your original regex to make it case-insensitive.)

I humbly ask that this change be made to the client, either making the current regex in create_child() case-insensitive or implementing my solution or a variation thereof.

Thanks!

**Comment by tamw-wnet** [comment]
Ahha!  Very interesting.  I will make the regex case-insensitive.   Very good bug to know about.

**Comment by tamw-wnet** [comment]
BTW, just changing line 235 should do it:
`preg_match("/(Location|URI): .*?\/([a-f0-9\-]+)\/(edit\/)?(\r|\n|\r\n)/", $result, $matches);`
to
`preg_match("/(Location|URI): .*?\/([a-f0-9\-]+)\/(edit\/)?(\r|\n|\r\n)/i", $result, $matches);`

**Comment by tamw-wnet** [comment]
not tested yet, however.

**Comment by tamw-wnet** [comment]
I have tested it and it at least works as well as it did previously.
