### ISSUE TITLE
Improved error handling

### ISSUE THREAD

**Issue by acrosman** [tamw-wnet/PBS_Media_Manager_Client#7]
Right now, when the API returns a 404 (or really any other error) while searching for assets the error response gets suppressed in get_child_assets()

    $result_data = array();
    $raw_result = $this->get_child_items_of_type($parent_id, $parent_type, 'asset', $queryargs);
    foreach ($raw_result as $result) {
      // only include the right asset_types
      if (!in_array($result['attributes']['object_type'], $asset_types)) {
        continue;
      }
    ...

I thought about just adding a detection for the error key provided in get_request() and having it return that element of the array at that point. But I realized that might have side effects to other code you might be using already, or cause other headaches I'm not thinking through, so I figured I'd stop and ask what your preferred approach to forwarding those errors would be?  

Seems the two primary options would be to make sure error elements of the array bubble up to the caller or throw an exception at get_request() and let it get caught and handled further up the stack. I don't mind either way but I'd like to be able to tell the difference between and empty response (which I've seen the API provide when no data is found) and a true error.

**Comment by tamw-wnet** [comment]
I have been thinking about -- and plan to -- actually return an 'errors' array when there's an error.  To my mind, a 404 is as much an error as anything else.   I don't have anything depending on it yet -- but @augustuswm may already have built code that expects something different.  My documentation specifies an errors array being returned as appropriate.

Assume that if there's a response code it will be included.

I just haven't had a moment to add that output, but actually it's pretty much next on my list -- if you hadn't made this issue I would've.

**Comment by augustuswm** [comment]
I think I have only a small piece of code that depends on this, but I don't think it would break. At this stage though I am in general all for breaking changes while figuring out what the interface looks like.

Once you are happy with the interface and think it is in a good place, then commit to backwards compatibility.

**Comment by tamw-wnet** [comment]
@augustuswm , here's where I'm thinking -- if the parent object (episode or whatever specified by the cid) does not exist, I'll return the errors array that I'm currently suppressing.    

If the parent object does exist but no matching assets exist, I'll return false.  

Does that work for everyone?

**Comment by augustuswm** [comment]
Not sure if this is what @acrosman meant, but I think there is the case to handle where an arbitrary page fails when going through pages ```1...n```. 

In that case does the whole query fail with the error, or does it return a partial collection?

In general I like treating anything that isn't 2xx as an error and using an empty list to denote the lack of elements.

**Comment by tamw-wnet** [comment]
I believe commit dd04f26 resolves this issue -- false for empty collection, errors array for problem with request.

**Comment by acrosman** [comment]
That commit does essentially what I'd been thinking of doing (and a bit more), so it looks just right to me.
